// Mock data for the application

// Issues
export const mockIssues = [
  {
    id: "1",
    title: "Climate Change Policy",
    description: "Advocating for stronger climate change policies and regulations.",
    category: "Environment",
    status: "Active",
    priority: "High",
    createdAt: "2023-01-15T00:00:00.000Z",
    updatedAt: "2023-06-10T00:00:00.000Z",
  },
  {
    id: "2",
    title: "Healthcare Reform",
    description: "Working on comprehensive healthcare reform to improve access and affordability.",
    category: "Healthcare",
    status: "Active",
    priority: "High",
    createdAt: "2023-02-20T00:00:00.000Z",
    updatedAt: "2023-07-05T00:00:00.000Z",
  },
  {
    id: "3",
    title: "Education Funding",
    description: "Advocating for increased education funding and resources for public schools.",
    category: "Education",
    status: "Active",
    priority: "Medium",
    createdAt: "2023-03-10T00:00:00.000Z",
    updatedAt: "2023-05-22T00:00:00.000Z",
  },
  {
    id: "4",
    title: "Affordable Housing",
    description: "Working to increase affordable housing options and reduce homelessness.",
    category: "Housing",
    status: "Active",
    priority: "Medium",
    createdAt: "2023-02-05T00:00:00.000Z",
    updatedAt: "2023-06-18T00:00:00.000Z",
  },
  {
    id: "5",
    title: "Criminal Justice Reform",
    description: "Advocating for reforms to the criminal justice system to address inequities.",
    category: "Justice",
    status: "Active",
    priority: "High",
    createdAt: "2023-01-30T00:00:00.000Z",
    updatedAt: "2023-07-12T00:00:00.000Z",
  },
  {
    id: "6",
    title: "Voting Rights Protection",
    description: "Working to protect and expand voting rights and access to the ballot.",
    category: "Democracy",
    status: "Active",
    priority: "High",
    createdAt: "2023-03-15T00:00:00.000Z",
    updatedAt: "2023-06-28T00:00:00.000Z",
  },
  {
    id: "7",
    title: "Immigration Reform",
    description: "Advocating for comprehensive immigration reform and protections for immigrants.",
    category: "Immigration",
    status: "Active",
    priority: "Medium",
    createdAt: "2023-04-10T00:00:00.000Z",
    updatedAt: "2023-07-08T00:00:00.000Z",
  },
  {
    id: "8",
    title: "Economic Inequality",
    description: "Working to address economic inequality and promote economic justice.",
    category: "Economy",
    status: "Active",
    priority: "Medium",
    createdAt: "2023-02-25T00:00:00.000Z",
    updatedAt: "2023-06-15T00:00:00.000Z",
  },
  {
    id: "9",
    title: "Gun Violence Prevention",
    description: "Advocating for policies to reduce gun violence and promote public safety.",
    category: "Public Safety",
    status: "Active",
    priority: "High",
    createdAt: "2023-03-05T00:00:00.000Z",
    updatedAt: "2023-07-01T00:00:00.000Z",
  },
  {
    id: "10",
    title: "LGBTQ+ Rights",
    description: "Working to protect and expand rights for LGBTQ+ individuals.",
    category: "Civil Rights",
    status: "Active",
    priority: "Medium",
    createdAt: "2023-04-20T00:00:00.000Z",
    updatedAt: "2023-06-25T00:00:00.000Z",
  },
  {
    id: "11",
    title: "Renewable Energy",
    description: "Advocating for increased investment in renewable energy sources.",
    category: "Environment",
    status: "Active",
    priority: "Medium",
    createdAt: "2023-05-05T00:00:00.000Z",
    updatedAt: "2023-07-10T00:00:00.000Z",
  },
  {
    id: "12",
    title: "Mental Health Services",
    description: "Working to improve access to mental health services and reduce stigma.",
    category: "Healthcare",
    status: "Active",
    priority: "Medium",
    createdAt: "2023-03-25T00:00:00.000Z",
    updatedAt: "2023-06-20T00:00:00.000Z",
  },
];

// Politicians
export const mockPoliticians = [
  {
    id: "1",
    name: "Jane Smith",
    position: "Senator",
    party: "Democratic",
    state: "California",
    district: "",
    contactEmail: "jane.smith@senate.gov",
    contactPhone: "202-555-0101",
    notes: "Strong supporter of environmental policies.",
    lastContact: "2023-06-15T00:00:00.000Z",
  },
  {
    id: "2",
    name: "John Doe",
    position: "Representative",
    party: "Republican",
    state: "Texas",
    district: "5",
    contactEmail: "john.doe@house.gov",
    contactPhone: "202-555-0102",
    notes: "Interested in healthcare reform from a market perspective.",
    lastContact: "2023-05-20T00:00:00.000Z",
  },
  {
    id: "3",
    name: "Maria Rodriguez",
    position: "Senator",
    party: "Democratic",
    state: "New York",
    district: "",
    contactEmail: "maria.rodriguez@senate.gov",
    contactPhone: "202-555-0103",
    notes: "Champion for education funding and reform.",
    lastContact: "2023-07-05T00:00:00.000Z",
  },
  {
    id: "4",
    name: "Robert Johnson",
    position: "Representative",
    party: "Democratic",
    state: "Illinois",
    district: "7",
    contactEmail: "robert.johnson@house.gov",
    contactPhone: "202-555-0104",
    notes: "Advocate for affordable housing initiatives.",
    lastContact: "2023-06-28T00:00:00.000Z",
  },
  {
    id: "5",
    name: "Sarah Williams",
    position: "Senator",
    party: "Republican",
    state: "Ohio",
    district: "",
    contactEmail: "sarah.williams@senate.gov",
    contactPhone: "202-555-0105",
    notes: "Interested in criminal justice reform from a conservative perspective.",
    lastContact: "2023-04-15T00:00:00.000Z",
  },
  {
    id: "6",
    name: "Michael Brown",
    position: "Representative",
    party: "Democratic",
    state: "Washington",
    district: "9",
    contactEmail: "michael.brown@house.gov",
    contactPhone: "202-555-0106",
    notes: "Strong advocate for voting rights and election security.",
    lastContact: "2023-07-10T00:00:00.000Z",
  },
  {
    id: "7",
    name: "Lisa Chen",
    position: "Senator",
    party: "Democratic",
    state: "Hawaii",
    district: "",
    contactEmail: "lisa.chen@senate.gov",
    contactPhone: "202-555-0107",
    notes: "Supportive of comprehensive immigration reform.",
    lastContact: "2023-06-05T00:00:00.000Z",
  },
  {
    id: "8",
    name: "David Wilson",
    position: "Representative",
    party: "Republican",
    state: "Florida",
    district: "12",
    contactEmail: "david.wilson@house.gov",
    contactPhone: "202-555-0108",
    notes: "Focused on economic growth and job creation.",
    lastContact: "2023-05-25T00:00:00.000Z",
  },
];

// Meetings/Interactions
export const mockMeetings = [
  {
    id: "1",
    title: "Climate Policy Discussion",
    date: "2023-06-15T14:00:00.000Z",
    type: "In-person",
    politicianId: "1",
    politicianName: "Jane Smith",
    issueId: "1",
    issueName: "Climate Change Policy",
    notes: "Discussed potential new climate legislation. Senator Smith expressed interest in co-sponsoring.",
    outcome: "Positive",
    followUpDate: "2023-07-01T00:00:00.000Z",
    followUpCompleted: true,
  },
  {
    id: "2",
    title: "Healthcare Reform Call",
    date: "2023-05-20T10:30:00.000Z",
    type: "Virtual",
    politicianId: "2",
    politicianName: "John Doe",
    issueId: "2",
    issueName: "Healthcare Reform",
    notes: "Rep. Doe shared concerns about cost implications but is open to further discussion.",
    outcome: "Neutral",
    followUpDate: "2023-06-15T00:00:00.000Z",
    followUpCompleted: true,
  },
  {
    id: "3",
    title: "Education Funding Meeting",
    date: "2023-07-05T13:00:00.000Z",
    type: "In-person",
    politicianId: "3",
    politicianName: "Maria Rodriguez",
    issueId: "3",
    issueName: "Education Funding",
    notes: "Senator Rodriguez committed to advocating for increased education funding in the next budget cycle.",
    outcome: "Positive",
    followUpDate: "2023-08-01T00:00:00.000Z",
    followUpCompleted: false,
  },
  {
    id: "4",
    title: "Affordable Housing Discussion",
    date: "2023-06-28T15:30:00.000Z",
    type: "In-person",
    politicianId: "4",
    politicianName: "Robert Johnson",
    issueId: "4",
    issueName: "Affordable Housing",
    notes: "Rep. Johnson shared his housing initiative and is interested in collaboration.",
    outcome: "Positive",
    followUpDate: "2023-07-15T00:00:00.000Z",
    followUpCompleted: false,
  },
  {
    id: "5",
    title: "Criminal Justice Reform Call",
    date: "2023-04-15T11:00:00.000Z",
    type: "Virtual",
    politicianId: "5",
    politicianName: "Sarah Williams",
    issueId: "5",
    issueName: "Criminal Justice Reform",
    notes: "Senator Williams expressed interest in bipartisan approaches to reform.",
    outcome: "Neutral",
    followUpDate: "2023-05-10T00:00:00.000Z",
    followUpCompleted: true,
  },
  {
    id: "6",
    title: "Voting Rights Meeting",
    date: "2023-07-10T14:30:00.000Z",
    type: "In-person",
    politicianId: "6",
    politicianName: "Michael Brown",
    issueId: "6",
    issueName: "Voting Rights Protection",
    notes: "Rep. Brown committed to supporting upcoming voting rights legislation.",
    outcome: "Positive",
    followUpDate: "2023-07-25T00:00:00.000Z",
    followUpCompleted: false,
  },
  {
    id: "7",
    title: "Immigration Reform Discussion",
    date: "2023-06-05T13:30:00.000Z",
    type: "Virtual",
    politicianId: "7",
    politicianName: "Lisa Chen",
    issueId: "7",
    issueName: "Immigration Reform",
    notes: "Senator Chen shared her immigration reform priorities and requested more information.",
    outcome: "Positive",
    followUpDate: "2023-06-20T00:00:00.000Z",
    followUpCompleted: true,
  },
  {
    id: "8",
    title: "Economic Policy Call",
    date: "2023-05-25T10:00:00.000Z",
    type: "Virtual",
    politicianId: "8",
    politicianName: "David Wilson",
    issueId: "8",
    issueName: "Economic Inequality",
    notes: "Rep. Wilson was skeptical about some proposals but open to discussing targeted economic initiatives.",
    outcome: "Neutral",
    followUpDate: "2023-06-10T00:00:00.000Z",
    followUpCompleted: true,
  },
  {
    id: "9",
    title: "Gun Violence Prevention Meeting",
    date: "2023-07-12T15:00:00.000Z",
    type: "In-person",
    politicianId: "1",
    politicianName: "Jane Smith",
    issueId: "9",
    issueName: "Gun Violence Prevention",
    notes: "Senator Smith expressed strong support for comprehensive background checks.",
    outcome: "Positive",
    followUpDate: "2023-07-30T00:00:00.000Z",
    followUpCompleted: false,
  },
  {
    id: "10",
    title: "LGBTQ+ Rights Discussion",
    date: "2023-06-20T11:30:00.000Z",
    type: "Virtual",
    politicianId: "3",
    politicianName: "Maria Rodriguez",
    issueId: "10",
    issueName: "LGBTQ+ Rights",
    notes: "Senator Rodriguez committed to co-sponsoring upcoming equality legislation.",
    outcome: "Positive",
    followUpDate: "2023-07-05T00:00:00.000Z",
    followUpCompleted: true,
  },
  {
    id: "11",
    title: "Renewable Energy Call",
    date: "2023-07-08T14:00:00.000Z",
    type: "Virtual",
    politicianId: "6",
    politicianName: "Michael Brown",
    issueId: "11",
    issueName: "Renewable Energy",
    notes: "Rep. Brown shared his support for renewable energy investments in his district.",
    outcome: "Positive",
    followUpDate: "2023-07-22T00:00:00.000Z",
    followUpCompleted: false,
  },
  {
    id: "12",
    title: "Mental Health Services Meeting",
    date: "2023-06-25T13:00:00.000Z",
    type: "In-person",
    politicianId: "4",
    politicianName: "Robert Johnson",
    issueId: "12",
    issueName: "Mental Health Services",
    notes: "Rep. Johnson expressed interest in expanding mental health services in underserved communities.",
    outcome: "Positive",
    followUpDate: "2023-07-10T00:00:00.000Z",
    followUpCompleted: false,
  },
];